library(tidyverse)
library(leaflet)
library(shiny)
library(shinythemes)
library(rsconnect)
library(shinyWidgets)
library(leaflet.extras)
library(shinydashboard)
library(shinydashboardPlus)
library(shinyEffects)
library(shinyjqui)
library(styler)
library(highcharter)
library(shinyAce)
library(shinyjs)
library(shinycssloaders)

VisitsOOHGeneral <- readRDS(file = "data/VisitsOOHGeneral.rds")
VisitsOOH <- readRDS(file = "data/VisitsOOH.rds")
VisitsOOHClientes <- readRDS(file = "data/VisitsOOHClientes.rds")
VisitsOOHConcorrentes <- readRDS(file = "data/VisitsOOHConcorrentes.rds")
VisitsOOHStore <- readRDS(file = "data/VisitsOOHStore.rds")
PlanningData <- readRDS(file = "data/PlanningData.rds")
Stores <- readRDS(file = "data/Stores.rds")

Storeicons <- makeIcon("www/store_icon.png", 30,38)

